import Head from "next/head";
import { useRef } from "react";
import Banner from "../components/Banner";
import Footer from "../components/Footer";
import Header from "../components/Header";
import LargeCard from "../components/LargeCard";
import MediumCard from "../components/MediumCard";
import SmallCard from "../components/SmallCard";
import { ChevronLeftIcon, ChevronRightIcon } from "@heroicons/react/outline";
import dataExplore from "../utils/dataExplore";
import dataCard from "../utils/dataCard";

export default function Home({ exploreData, cardsData }) {
  const hscroll = useRef(null);

  const moveRight = () => {
    const el = hscroll.current;
    return (el.scrollLeft += 800);
  };

  const moveLeft = () => {
    const el = hscroll.current;
    return (el.scrollLeft -= 800);
  };

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section className="pt-6">
          <h2 className="text-4xl font-semibold pb-5">Explore Nearby</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, location, distance }) => (
              <SmallCard
                key={img}
                img={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>
        <section className="pt-6">
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>
          <div
            ref={hscroll}
            className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3 scroll-smooth"
          >
            {cardsData?.map(({ img, title }) => (
              <MediumCard key={img} img={img} title={title} />
            ))}
          </div>
          <div
            className="relative hidden md:flex justify-between z-20 px-8"
            style={{ marginTop: -230, marginBottom: 230 }}
          >
            <ChevronLeftIcon
              onClick={moveLeft}
              className="text-gray-900 bg-white bg-opacity-60 rounded-full p-2 w-10 h-10 cursor-pointer"
            />
            <ChevronRightIcon
              onClick={moveRight}
              className="text-gray-900 bg-white bg-opacity-60 rounded-full p-2 w-10 h-10 cursor-pointer"
            />
          </div>
        </section>

        <LargeCard
          img="https://links.papareact.com/4cj"
          title="The Greatest Outdoors"
          description="Whistlist curated by Airbnb."
          buttonText="Get Inspired"
        />
      </main>

      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  console.log("get cookies: ", context.req.cookies);
  const urls = [
    "https://links.papareact.com/pyp",
    "https://links.papareact.com/zp1",
  ];

  try {
    const response = await Promise.all(
      urls.map(async (promise) => {
        const dataFetch = await fetch(promise);
        const dataJson = await dataFetch.json();

        return dataJson;
      })
    );

    const dataObj = response.reduce((accumulator, value, index) => {
      return { ...accumulator, [`data${index + 1}`]: value };
    }, {});

    return {
      props: {
        exploreData: dataObj.data1,
        cardsData: dataObj.data2,
      },
    };
  } catch (error) {
    console.log("error fetch: ", error);

    return {
      props: {
        exploreData: dataExplore,
        cardsData: dataCard,
      },
    };
  }
}
